### PR TITLE
커맨드 라인 실행 예시 수정

### PR DESCRIPTION
**Pull request by waihekedays**
검토해주세요.

### CODE REVIEW

**Comment by fharenheit** [comment]
Sample2Driver는 실행시켜보셨는지요? --로 옵션이 들어가고 짧은 것이 -로 들어가야합니다.

**Comment by fharenheit** [comment]
SampleDriver는 --가 아닌 -가 맞습니다.

**Comment by waihekedays** [comment]
본부장님, 안녕하세요^^
-- 가 좋을것 같네요.

-- 랑 - 둘 다 돌아가긴하더라고요.


그리고 질문이 하나 있는데요...
옵션으로 지정해준 job.name이 뭔지 잘 모르겠어요.
왠지 아래 job title 에 반영될줄 알았는데 값이 다르네요.



저 github 가 익숙하지 않아서 실습 한 번 해봤습니다.
무시하셔도 되여~

고맙습니다.
김은영 드림



[ec2-user@ip-172-31-48-224 ~]$ *hadoop jar
mapreduce-template-0.2-SNAPSHOT.jar
org.openflamingo.mapreduce.sample.Sample2Driver -Dmapred.job.name
<http://Dmapred.job.name>="Test MapReduce Job" -input
/user/waiheke/sample2/input -output /user/waiheke/sample2/output15
-delimiter " "*
16/05/22 03:13:04 INFO client.RMProxy: Connecting to ResourceManager at
ec2-54-173-216-72.compute-1.amazonaws.com/172.31.48.224:8032
16/05/22 03:13:05 WARN mapreduce.JobResourceUploader: Hadoop command-line
option parsing not performed. Implement the Tool interface and execute your
application with ToolRunner to remedy this.
16/05/22 03:13:05 INFO input.FileInputFormat: Total input paths to process
: 2
16/05/22 03:13:05 INFO mapreduce.JobSubmitter: number of splits:2
16/05/22 03:13:06 INFO mapreduce.JobSubmitter: Submitting tokens for job:
job_1463723595472_0022
16/05/22 03:13:06 INFO impl.YarnClientImpl: Submitted application
application_1463723595472_0022
16/05/22 03:13:06 INFO mapreduce.Job: The url to track the job:
http://ec2-54-173-216-72.compute-1.amazonaws.com:8088/proxy/application_1463723595472_0022/
16/05/22 03:13:06 INFO mapreduce.Job: *Running job: job_1463723595472_0022*
16/05/22 03:13:14 INFO mapreduce.Job: Job job_1463723595472_0022 running in
uber mode : false
16/05/22 03:13:14 INFO mapreduce.Job:  map 0% reduce 0%
16/05/22 03:13:26 INFO mapreduce.Job:  map 100% reduce 0%
16/05/22 03:13:26 INFO mapreduce.Job: Job job_1463723595472_0022 completed
successfully
16/05/22 03:13:26 INFO mapreduce.Job: Counters: 30
File System Counters
FILE: Number of bytes read=0
FILE: Number of bytes written=230710
FILE: Number of read operations=0
FILE: Number of large read operations=0
FILE: Number of write operations=0
HDFS: Number of bytes read=356
HDFS: Number of bytes written=4
HDFS: Number of read operations=10
HDFS: Number of large read operations=0
HDFS: Number of write operations=4
Job Counters
Launched map tasks=2
Data-local map tasks=2
Total time spent by all maps in occupied slots (ms)=19505
Total time spent by all reduces in occupied slots (ms)=0
Total time spent by all map tasks (ms)=19505
Total vcore-seconds taken by all map tasks=19505
Total megabyte-seconds taken by all map tasks=19973120
Map-Reduce Framework
Map input records=4
Map output records=4
Input split bytes=304
Spilled Records=0
Failed Shuffles=0
Merged Map outputs=0
GC time elapsed (ms)=102
CPU time spent (ms)=1200
Physical memory (bytes) snapshot=209252352
Virtual memory (bytes) snapshot=1906204672
Total committed heap usage (bytes)=31588352
File Input Format Counters
Bytes Read=52
File Output Format Counters
Bytes Written=4




2016-05-22 12:02 GMT+09:00 Edward KIM <notifications@github.com>:

**Comment by fharenheit** [comment]
mapred.job.name을 주면 job title이 변경이 될꺼에요 근데 안자뀐다고 하니... 음

2016년 5월 22일 일요일, waihekedays<notifications@github.com>님이 작성한 메시지:

> 본부장님, 안녕하세요^^
> -- 가 좋을것 같네요.
>
> -- 랑 - 둘 다 돌아가긴하더라고요.
>
>
> 그리고 질문이 하나 있는데요...
> 옵션으로 지정해준 job.name이 뭔지 잘 모르겠어요.
> 왠지 아래 job title 에 반영될줄 알았는데 값이 다르네요.
>
>
>
> 저 github 가 익숙하지 않아서 실습 한 번 해봤습니다.
> 무시하셔도 되여~
>
> 고맙습니다.
> 김은영 드림
>
>
>
> [ec2-user@ip-172-31-48-224 ~]$ *hadoop jar
> mapreduce-template-0.2-SNAPSHOT.jar
> org.openflamingo.mapreduce.sample.Sample2Driver -Dmapred.job.name
> <http://Dmapred.job.name>="Test MapReduce Job" -input
> /user/waiheke/sample2/input -output /user/waiheke/sample2/output15
> -delimiter " "*
> 16/05/22 03:13:04 INFO client.RMProxy: Connecting to ResourceManager at
> ec2-54-173-216-72.compute-1.amazonaws.com/172.31.48.224:8032
> 16/05/22 03:13:05 WARN mapreduce.JobResourceUploader: Hadoop command-line
> option parsing not performed. Implement the Tool interface and execute your
> application with ToolRunner to remedy this.
> 16/05/22 03:13:05 INFO input.FileInputFormat: Total input paths to process
> : 2
> 16/05/22 03:13:05 INFO mapreduce.JobSubmitter: number of splits:2
> 16/05/22 03:13:06 INFO mapreduce.JobSubmitter: Submitting tokens for job:
> job_1463723595472_0022
> 16/05/22 03:13:06 INFO impl.YarnClientImpl: Submitted application
> application_1463723595472_0022
> 16/05/22 03:13:06 INFO mapreduce.Job: The url to track the job:
>
> http://ec2-54-173-216-72.compute-1.amazonaws.com:8088/proxy/application_1463723595472_0022/
> 16/05/22 03:13:06 INFO mapreduce.Job: *Running job: job_1463723595472_0022*
> 16/05/22 03:13:14 INFO mapreduce.Job: Job job_1463723595472_0022 running in
> uber mode : false
> 16/05/22 03:13:14 INFO mapreduce.Job: map 0% reduce 0%
> 16/05/22 03:13:26 INFO mapreduce.Job: map 100% reduce 0%
> 16/05/22 03:13:26 INFO mapreduce.Job: Job job_1463723595472_0022 completed
> successfully
> 16/05/22 03:13:26 INFO mapreduce.Job: Counters: 30
> File System Counters
> FILE: Number of bytes read=0
> FILE: Number of bytes written=230710
> FILE: Number of read operations=0
> FILE: Number of large read operations=0
> FILE: Number of write operations=0
> HDFS: Number of bytes read=356
> HDFS: Number of bytes written=4
> HDFS: Number of read operations=10
> HDFS: Number of large read operations=0
> HDFS: Number of write operations=4
> Job Counters
> Launched map tasks=2
> Data-local map tasks=2
> Total time spent by all maps in occupied slots (ms)=19505
> Total time spent by all reduces in occupied slots (ms)=0
> Total time spent by all map tasks (ms)=19505
> Total vcore-seconds taken by all map tasks=19505
> Total megabyte-seconds taken by all map tasks=19973120
> Map-Reduce Framework
> Map input records=4
> Map output records=4
> Input split bytes=304
> Spilled Records=0
> Failed Shuffles=0
> Merged Map outputs=0
> GC time elapsed (ms)=102
> CPU time spent (ms)=1200
> Physical memory (bytes) snapshot=209252352
> Virtual memory (bytes) snapshot=1906204672
> Total committed heap usage (bytes)=31588352
> File Input Format Counters
> Bytes Read=52
> File Output Format Counters
> Bytes Written=4
>
>
>
>
> 2016-05-22 12:02 GMT+09:00 Edward KIM <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > SampleDriver는 --가 아닌 -가 맞습니다.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/fharenheit/template-mapreduce/pull/1#issuecomment-220811707
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/fharenheit/template-mapreduce/pull/1#issuecomment-220812068>
>


-- 

========================================================================

| Flamingo | 누구나 기술의 장벽없이 세상의 데이터를 다룰 수 있는 오픈소스 빅데이터 플랫폼

========================================================================

(주) 클라우다인 대표이사 김병곤

빅데이터 전문가협의회 수석 부의장

Open Cloud Engine Leader

Flamingo Founder

Email : fharenheit@gmail.com

Google Talk. fharenheit@gmail.com

Mobile. 010-4666-9321 (회사), 010-9896-9321 (개인)

========================================================================

**Comment by waihekedays** [comment]
네 제가 hadoop 도 안익숙해서요.
더 찾아볼게요~ 고맙습니다.

2016년 5월 22일 일요일, Edward KIM<notifications@github.com>님이 작성한 메시지:

**Pull request merged**
